#!/bin/bash
# configuring usernames
git config --global user.name "Brunno dos Santos"
git config --global user.email "squiter85@gmail.com"

# use the new behavior for push
git config --global push.default simple

# do not change crlf configuration
git config --global core.autocrlf false
